### ISSUE TITLE
The code requires PHP 5.6

### ISSUE THREAD

**Issue by ravage84** [steinkel/cakefest2016#1]
This code actually requires PHP 5.6, even though the composer.json states otherwise.
The defined array as constant at
https://github.com/steinkel/cakefest2016/blob/7b47168cdf520d7bac4e525dbfb48ed8e4c0fee1/plugins/Newsletter/src/Model/Table/CampaignsTable.php#L22
leads to a 
``Fatal error: Arrays are not allowed in class constants in path\to\app\\plugins\Newsletter\src\Model\Table\CampaignsTable.php on line 19`` on PHP 5.5.

http://stackoverflow.com/questions/1290318/php-constants-containing-arrays

**Comment by steinkel** [comment]
Thank you for pointing that out!

You gave me a reason to add a couple improvements related to Enums, let me know if it's looking better now.

Closed per #2
